vim.api.nvim_create_autocmd("User", {
    pattern = "TSUpdate",
    callback = function()
        require("nvim-treesitter.parsers").asciidoc = {
            install_info = {
                url = "https://github.com/cathaysia/tree-sitter-asciidoc",
                branch = "master",
                location = "tree-sitter-asciidoc", -- only needed if the parser is in subdirectory of a "monorepo"
                queries = "queries/asciidoc", -- also install queries from given directory
                requires = { "asciidoc_inline" },
            },
        }
        require("nvim-treesitter.parsers").asciidoc_inline = {
            install_info = {
                url = "https://github.com/cathaysia/tree-sitter-asciidoc",
                branch = "master",
                location = "tree-sitter-asciidoc_inline",
                queries = "queries/asciidoc_inline",
            },
        }
    end,
})

local ensure_install = {
    "asciidoc",
    "asciidoc_inline",
    "bash",
    "caddy",
    "comment",
    "css",
    "csv",
    "diff",
    "dockerfile",
    "editorconfig",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "gpg",
    "graphql",
    "groovy",
    "groq",
    "hjson",
    "html",
    "html_tags",
    "http",
    "ini",
    "java",
    "javadoc",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "jsx",
    "just",
    "kdl",
    "kitty",
    "latex",
    "lua",
    "markdown",
    "markdown_inline",
    "mermaid",
    "meson",
    "nginx",
    "nix",
    "perl",
    "python",
    "regex",
    "requirements",
    "robot",
    "robots_txt",
    "ron",
    "rst",
    "ruby",
    "rust",
    "scss",
    "sql",
    "ssh_config",
    "swift",
    "tmux",
    "toml",
    "tsv",
    "typescript",
    "typst",
    "vim",
    "vimdoc",
    "vue",
    "xml",
    "yaml",
    "zsh",
}

require("nvim-treesitter").install(ensure_install)
